// generated by Pantheas.ApiDefinitionGenerator.Generator
using System.Net.Http;
namespace Pantheas.CupsApi.Generated.Definition;
public class CupsDefinition
{
    public class GetAllCups
    {
        public string Route { get; }
        public HttpMethod Method { get; }
        public GetAllCups()
        {
            Route = "cups";
            Method = new HttpMethod("GET");
        }
    }
    public class DeleteCup
    {
        public string Route { get; }
        public HttpMethod Method { get; }
        public DeleteCup(int id)
        {
            Route = $"cups/{id}";
            Method = new HttpMethod("DELETE");
        }
    }
    public class CreateCup
    {
        public string Route { get; }
        public HttpMethod Method { get; }
        public CreateCup()
        {
            Route = "cups";
            Method = new HttpMethod("POST");
        }
    }
}
